name: macOS build
run-name: macOS build
on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: macos-latest
    env:
      MACOS_SIGNING_IDENTITY: ${{ secrets.MACOS_SIGNING_IDENTITY }}
    steps:
      - name: Prep notarization
        env: 
          APPLE_NOTARY_API_KEY: ${{ secrets.APPLE_NOTARY_API_KEY }}
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          MACOS_KEYCHAIN_PWD: ${{ secrets.MACOS_KEYCHAIN_PWD }}
        run: |
          set -e
          echo "$MACOS_CERTIFICATE" | base64 --decode > certificate.p12
          echo "$APPLE_NOTARY_API_KEY" | base64 --decode > notary_api_key.p8
          security create-keychain -p "$MACOS_KEYCHAIN_PWD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$MACOS_KEYCHAIN_PWD" build.keychain
          security import certificate.p12 -k build.keychain -P "$MACOS_CERTIFICATE_PWD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$MACOS_KEYCHAIN_PWD" build.keychain

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Install vcpkg dependencies
        uses: lukka/run-vcpkg@v11

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.7.0
          host: mac
          target: desktop
          arch: clang_64

      - name: CMake
        run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=arm64-osx -DVCPKG_BUILD_TYPE=release

      - name: Build
        run: cmake --build build --config Release

      - name: macdeployqt
        run: macdeployqt Comet.app -sign-for-notarization="$MACOS_SIGNING_IDENTITY" -dmg 
        working-directory: build

      - name: List all files recursively
        run: |
          echo "Listing all files recursively"
          find $(pwd)

      - name: Notarize DMG
        env:
          APPLE_NOTARY_API_KEY_ID: ${{ secrets.APPLE_NOTARY_API_KEY_ID }}
          APPLE_NOTARY_API_ISSUER_ID: ${{ secrets.APPLE_NOTARY_API_ISSUER_ID }}
        run: |
          xcrun notarytool submit build/Comet.dmg \
            --key notary_api_key.p8 \
            --key-id "$APPLE_NOTARY_API_KEY_ID" \
            --issuer "$APPLE_NOTARY_API_ISSUER_ID" \
            --wait

      - name: Staple Notarization Ticket
        run: xcrun stapler staple build/Comet.dmg

      - name: Verify Stapling
        run: |
          xcrun stapler validate build/Comet.dmg

      - name: Upload build as artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: Comet-macOS-arm64
          path: build/Comet.dmg
