name: Build Comet for Windows
run-name: ${{ github.actor }} is building Comet for Windows
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: vcpkg-action
        uses: johnwason/vcpkg-action@v6
        with:
          token: ${{ github.token }}
      - id: install-qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.7.0
          host: windows
          target: desktop
          arch: win64_msvc2019_64
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: CMake
        run: cmake . -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_OSX_ARCHITECTURES="x86_64" -DVCPKG_TARGET_TRIPLET=x64-windows-release
