name: PR build
run-name: ${{ github.actor }} PR build
on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install CMake
      - uses: lukka/get-cmake@latest

      - name: Install vcpkg dependencies
        uses: lukka/run-vcpkg@v11

      # - name: Add msbuild to PATH
      #   uses: microsoft/setup-msbuild@v2

      # - name: Install Qt
      #   uses: jurplel/install-qt-action@v3
      #   with:
      #     version: 6.7.0
      #     host: windows
      #     target: desktop
      #     arch: win64_msvc2019_64

      - name: List files
        run: find .

      - name: CMake
        run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=arm64-osx-release

      - name: msbuild
        run: msbuild build\Comet.sln /property:Configuration=Release

      - name: windeployqt
        run: windeployqt --release build\Release\Comet.exe

      - name: Upload build as artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: Comet-Windows-x64
          path: build\Release

      - name: Zip build artifacts
        if: startsWith(github.ref, 'refs/tags/')
        shell: powershell
        run: |
          Compress-Archive -Path build\Release\* -DestinationPath build\Comet.zip

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: build\Comet.zip
