name: PR build
run-name: ${{ github.actor }} PR build
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install vcpkg dependencies
        uses: lukka/run-vcpkg@v11

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.7.0
          host: windows
          target: desktop
          arch: win64_msvc2019_64

      - name: CMake
        run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-release

      - name: msbuild
        run: msbuild build\Comet.sln /property:Configuration=Release

      - name: windeployqt
        run: windeployqt --release build\Release\Comet.exe

      - name: Zip the build output
        run: Compress-Archive -Path build\Release\* -DestinationPath build\Release\Comet-Windows-x64.zip

      - name: Upload build as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Comet-Windows-x64
          path: build\Release\Comet-Windows-x64.zip
